export const criteriosSelecaoSugeridos = [
  "Preço",
  "Preço competitivo",
  "Preço global",
  "Preço por hora-equipe",
  "Preço por prensa",
  "Preço por tonelada",
  "Preço unitário",
  "Qualidade técnica",
  "Qualificação técnica",
  "Capacidade técnica",
  "Experiência comprovada em mineração",
  "Experiência metalúrgica",
  "Experiência setorial",
  "Experiência em içamento",
  "Conformidade ambiental",
  "Multidisciplinaridade da equipe",
  "Prazo",
  "Prazo de entrega",
  "Prazo de execução",
  "Prazo de parada",
  "Prazo de mobilização",
  "Tempo de implantação",
  "Capacidade logística",
  "Capacidade especializada",
  "Capacidade de frota",
  "Disponibilidade imediata",
  "Disponibilidade de equipe técnica",
  "Portfólio",
  "Portfólio de obras semelhantes",
  "Qualidade do laudo",
  "Precisão dimensional",
  "Didática",
  "Certificação",
  "SLA de pontualidade",
  "Seguro",
] as const;

export const documentosProjetoSugeridos = [
  "ART",
  "ART de responsabilidade técnica",
  "ART luminotécnica",
  "ART mecânica",
  "ART NR-12",
  "Apólice de seguro",
  "Apólice de seguro de carga",
  "Alvará de construção",
  "Certificado de Aprovação (CA)",
  "Certificado NR-10",
  "Certificado NR-10 SEP",
  "Certificado NR-11",
  "Certificado NR-13",
  "Certificado NR-22",
  "Certificação ISO 14001",
  "Certificação OHSAS 18001",
  "Certificado de instrutor NR-35",
  "Certificado de destinação final",
  "EPS/PQR de soldagem",
  "Ficha de segurança (FISPQ)",
  "Laudo de inspeção NR-12",
  "Laudo de ventilação",
  "Laudo técnico",
  "Laudo técnico dos consumíveis",
  "Licença ambiental",
  "Licença IBAMA",
  "Plano de instalação",
  "Plano de gerenciamento de resíduos",
  "Portfólio de contratos similares",
  "Portfólio de retrofit similar",
  "Registro CREA",
  "Registro do engenheiro responsável",
  "Registro no MTE",
  "Relatório dimensional",
  "RNTRC",
] as const;

export const requisitosTecnicosSugeridos = [
  "Alvará de construção",
  "Caldeiraria pesada",
  "Capacidade de entrega mensal",
  "Certificação ISO 14001",
  "Controle dimensional",
  "CREA-MG",
  "Cumprimento de normas ANVISA",
  "Engenheiro ambiental responsável",
  "Engenheiro de segurança",
  "Engenheiro de segurança registrado no MTE",
  "Engenheiro mecânico responsável",
  "Equipe com eletricista de alta tensão (NR-10 SEP)",
  "Equipe com engenheiro ambiental",
  "Equipe de montagem industrial",
  "Equipe multidisciplinar",
  "Espaço para treinamento prático",
  "Estoque mínimo de segurança",
  "Experiência em equipamentos de içamento",
  "Experiência em exaustão industrial pesada",
  "Experiência em fornos de indução",
  "Experiência em monitoramento ambiental",
  "Experiência em NR-12 em prensas",
  "Experiência em obras industriais",
  "Experiência mínima de 5 anos em mineração",
  "Homologação prévia dos consumíveis",
  "Inspetor certificado",
  "Inspetor de solda certificado",
  "Laudo técnico assinado",
  "Licença ambiental vigente",
  "Licença para transporte de carga especial",
  "Material didático",
  "Médico do trabalho",
  "NR-10",
  "NR-10 SEP",
  "NR-11",
  "NR-12",
  "NR-13",
  "NR-15",
  "NR-22",
  "NR-35",
  "Plano de gerenciamento de resíduos",
  "Projeto luminotécnico",
  "Rastreabilidade de lote por laudo",
  "Rastreabilidade do material",
  "Registro no MTE",
  "Relatório dimensional",
  "RNTRC",
  "Seguro de carga",
  "Seguro de responsabilidade civil",
  "Soldador MIG/MAG qualificado",
  "Usinagem pesada",
] as const;
