import type { ReviewStatus } from "./_shared";

export interface Review {
  id: string;
  contrato_id: string;
  autor_membro_id: string;
  avaliado_org_tipo: "empresa" | "fornecedor";
  avaliado_org_id: string;
  notas: { [dimensao_id: string]: 1 | 2 | 3 | 4 | 5 };
  comentario: string;
  status: ReviewStatus;
  submetida_em?: string;
  liberada_em?: string;
}

export const reviews: Review[] = [
  // ct-7 — par liberado
  {
    id: "rev-ct-7-empresa",
    contrato_id: "ct-7",
    autor_membro_id: "mem-vale-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-techminas",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Excelente equipe, serviço entregue no prazo e dentro das especificações. Recomendamos fortemente.",
    status: "liberada",
    submetida_em: "2026-03-13",
    liberada_em: "2026-03-15",
  },
  {
    id: "rev-ct-7-fornecedor",
    contrato_id: "ct-7",
    autor_membro_id: "mem-techminas-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-vale",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 4,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Processo muito organizado. Pagamento dentro do combinado.",
    status: "liberada",
    submetida_em: "2026-03-14",
    liberada_em: "2026-03-15",
  },
  // ct-10 — par liberado
  {
    id: "rev-ct-10-empresa",
    contrato_id: "ct-10",
    autor_membro_id: "mem-arcelormittal-owner",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-ambiental-solutions",
    notas: {
      execucao: 4,
      prazo_execucao: 5,
      seguranca: 4,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Entregaram o RIMA dentro do prazo com documentação completa e precisa. Recomendamos.",
    status: "liberada",
    submetida_em: "2026-03-16",
    liberada_em: "2026-03-18",
  },
  {
    id: "rev-ct-10-fornecedor",
    contrato_id: "ct-10",
    autor_membro_id: "mem-ambiental-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-arcelormittal",
    notas: {
      pagamento: 5,
      clareza_escopo: 4,
      respeito_cronograma: 5,
      comunicacao_empresa: 4,
      relacionamento_empresa: 5,
    },
    comentario: "Escopo podia ser mais detalhado inicialmente, mas suporte da equipe foi ótimo.",
    status: "liberada",
    submetida_em: "2026-03-17",
    liberada_em: "2026-03-18",
  },
  // ct-11 — apenas 1 submetida (aguardando par)
  {
    id: "rev-ct-11-empresa",
    contrato_id: "ct-11",
    autor_membro_id: "mem-vale-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-translog",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Transporte especializado executado com perfeição. Equipamentos chegaram sem nenhum incidente e no prazo exato.",
    status: "submetida",
    submetida_em: "2026-04-08",
  },
  // ct-12 — ambas em rascunho
  {
    id: "rev-ct-12-empresa",
    contrato_id: "ct-12",
    autor_membro_id: "mem-usiminas-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-construminas",
    notas: {
      execucao: 4,
      prazo_execucao: 3,
      seguranca: 4,
      comunicacao_fornecedor: 3,
      relacionamento_fornecedor: 4,
    },
    comentario:
      "Qualidade boa, mas houve atrasos que impactaram o cronograma. Comunicação poderia melhorar.",
    status: "rascunho",
  },
  {
    id: "rev-ct-12-fornecedor",
    contrato_id: "ct-12",
    autor_membro_id: "mem-construminas-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-usiminas",
    notas: {
      pagamento: 3,
      clareza_escopo: 3,
      respeito_cronograma: 3,
      comunicacao_empresa: 3,
      relacionamento_empresa: 4,
    },
    comentario: "Pagamentos com atraso prejudicaram o cronograma de compras.",
    status: "rascunho",
  },
  // ct-13 — par liberado
  {
    id: "rev-ct-13-empresa",
    contrato_id: "ct-13",
    autor_membro_id: "mem-vale-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-segwork",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "PGR implementado com excelência técnica. Equipe extremamente qualificada e proativa em todo o processo.",
    status: "liberada",
    submetida_em: "2026-04-10",
    liberada_em: "2026-04-11",
  },
  {
    id: "rev-ct-13-fornecedor",
    contrato_id: "ct-13",
    autor_membro_id: "mem-segwork-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-vale",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 5,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Parceria excelente — engajamento total do time da Vale.",
    status: "liberada",
    submetida_em: "2026-04-10",
    liberada_em: "2026-04-11",
  },
  // ct-14 — par liberado
  {
    id: "rev-ct-14-empresa",
    contrato_id: "ct-14",
    autor_membro_id: "mem-arcelormittal-owner",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-segwork",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Treinamento impecável. Todos os colaboradores aprovados na primeira tentativa. Instrutores muito didáticos.",
    status: "liberada",
    submetida_em: "2026-03-09",
    liberada_em: "2026-03-11",
  },
  {
    id: "rev-ct-14-fornecedor",
    contrato_id: "ct-14",
    autor_membro_id: "mem-segwork-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-arcelormittal",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 5,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Logística da ArcelorMittal excelente. Recebemos tudo o necessário no prazo.",
    status: "liberada",
    submetida_em: "2026-03-10",
    liberada_em: "2026-03-11",
  },
  // ct-15 — vale ↔ techminas
  {
    id: "rev-ct-15-empresa",
    contrato_id: "ct-15",
    autor_membro_id: "mem-vale-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-techminas",
    notas: {
      execucao: 5,
      prazo_execucao: 4,
      seguranca: 5,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Troca de correias entregue com qualidade técnica alta. Cronograma escorregou 3 dias mas foi absorvido sem impacto operacional.",
    status: "liberada",
    submetida_em: "2025-12-01",
    liberada_em: "2025-12-03",
  },
  {
    id: "rev-ct-15-fornecedor",
    contrato_id: "ct-15",
    autor_membro_id: "mem-techminas-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-vale",
    notas: {
      pagamento: 5,
      clareza_escopo: 4,
      respeito_cronograma: 5,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Escopo evoluiu durante a execução mas o time foi muito colaborativo na adaptação.",
    status: "liberada",
    submetida_em: "2025-12-02",
    liberada_em: "2025-12-03",
  },
  // ct-16 — vale ↔ ambiental
  {
    id: "rev-ct-16-empresa",
    contrato_id: "ct-16",
    autor_membro_id: "mem-vale-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-ambiental-solutions",
    notas: {
      execucao: 4,
      prazo_execucao: 4,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Plano de recuperação de área degradada bem estruturado. Diagnóstico inicial demorou mais do que o esperado.",
    status: "liberada",
    submetida_em: "2026-02-27",
    liberada_em: "2026-02-28",
  },
  {
    id: "rev-ct-16-fornecedor",
    contrato_id: "ct-16",
    autor_membro_id: "mem-ambiental-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-vale",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 4,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Excelente documentação técnica no briefing. Liberação de acesso à área demorou.",
    status: "liberada",
    submetida_em: "2026-02-27",
    liberada_em: "2026-02-28",
  },
  // ct-17 — vale ↔ segwork
  {
    id: "rev-ct-17-empresa",
    contrato_id: "ct-17",
    autor_membro_id: "mem-vale-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-segwork",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Treinamentos NR-10 e NR-35 com 100% de aprovação. Material didático de alto nível.",
    status: "liberada",
    submetida_em: "2026-03-22",
    liberada_em: "2026-03-23",
  },
  {
    id: "rev-ct-17-fornecedor",
    contrato_id: "ct-17",
    autor_membro_id: "mem-segwork-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-vale",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 5,
      comunicacao_empresa: 4,
      relacionamento_empresa: 5,
    },
    comentario: "Engajamento total da equipe nos treinamentos. Troca de agenda de última hora exigiu replanejamento.",
    status: "liberada",
    submetida_em: "2026-03-22",
    liberada_em: "2026-03-23",
  },
  // ct-18 — vale ↔ metalurgica-xyz (fornecedor)
  {
    id: "rev-ct-18-empresa",
    contrato_id: "ct-18",
    autor_membro_id: "mem-vale-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-metalurgica-xyz",
    notas: {
      execucao: 4,
      prazo_execucao: 4,
      seguranca: 4,
      comunicacao_fornecedor: 3,
      relacionamento_fornecedor: 4,
    },
    comentario:
      "Usinagem dentro das especificações. Comunicação durante a execução poderia ser mais proativa.",
    status: "liberada",
    submetida_em: "2025-11-02",
    liberada_em: "2025-11-04",
  },
  {
    id: "rev-ct-18-fornecedor",
    contrato_id: "ct-18",
    autor_membro_id: "mem-metalurgica-xyz-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-vale",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 5,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Primeira experiência com a Vale extremamente positiva. Processo organizado do início ao fim.",
    status: "liberada",
    submetida_em: "2025-11-03",
    liberada_em: "2025-11-04",
  },
  // ct-19 — vale ↔ translog
  {
    id: "rev-ct-19-empresa",
    contrato_id: "ct-19",
    autor_membro_id: "mem-vale-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-translog",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Transporte de equipamentos pesados executado sem uma única intercorrência. Rastreamento impecável.",
    status: "liberada",
    submetida_em: "2026-03-24",
    liberada_em: "2026-03-25",
  },
  {
    id: "rev-ct-19-fornecedor",
    contrato_id: "ct-19",
    autor_membro_id: "mem-translog-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-vale",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 5,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Logística coordenada com precisão pela equipe da Vale. Pagamentos pontuais.",
    status: "liberada",
    submetida_em: "2026-03-24",
    liberada_em: "2026-03-25",
  },
  // ct-20 — arcelormittal ↔ translog
  {
    id: "rev-ct-20-empresa",
    contrato_id: "ct-20",
    autor_membro_id: "mem-arcelormittal-owner",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-translog",
    notas: {
      execucao: 4,
      prazo_execucao: 4,
      seguranca: 5,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 4,
    },
    comentario:
      "Atendimento correto. Alguns atrasos em rotas de longa distância, mas cronograma recuperado.",
    status: "liberada",
    submetida_em: "2025-12-20",
    liberada_em: "2025-12-22",
  },
  {
    id: "rev-ct-20-fornecedor",
    contrato_id: "ct-20",
    autor_membro_id: "mem-translog-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-arcelormittal",
    notas: {
      pagamento: 5,
      clareza_escopo: 4,
      respeito_cronograma: 4,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Parceria sólida. Janelas de carga poderiam ter mais folga para absorver imprevistos.",
    status: "liberada",
    submetida_em: "2025-12-21",
    liberada_em: "2025-12-22",
  },
  // ct-21 — arcelormittal ↔ construminas
  {
    id: "rev-ct-21-empresa",
    contrato_id: "ct-21",
    autor_membro_id: "mem-arcelormittal-owner",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-construminas",
    notas: {
      execucao: 4,
      prazo_execucao: 3,
      seguranca: 5,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 4,
    },
    comentario:
      "Obra de adequação industrial entregue com qualidade. Houve atraso de 2 semanas em função de chuvas.",
    status: "liberada",
    submetida_em: "2026-03-29",
    liberada_em: "2026-03-30",
  },
  {
    id: "rev-ct-21-fornecedor",
    contrato_id: "ct-21",
    autor_membro_id: "mem-construminas-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-arcelormittal",
    notas: {
      pagamento: 4,
      clareza_escopo: 4,
      respeito_cronograma: 4,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Acompanhamento diário da obra facilitou os ajustes. Fluxo de pagamento com 1 atraso pontual.",
    status: "liberada",
    submetida_em: "2026-03-29",
    liberada_em: "2026-03-30",
  },
  // ct-22 — arcelormittal ↔ techminas
  {
    id: "rev-ct-22-empresa",
    contrato_id: "ct-22",
    autor_membro_id: "mem-arcelormittal-owner",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-techminas",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 4,
    },
    comentario:
      "Revisão completa dos redutores da linha 2 entregue antes do prazo. Relatório técnico muito completo.",
    status: "liberada",
    submetida_em: "2026-04-06",
    liberada_em: "2026-04-07",
  },
  {
    id: "rev-ct-22-fornecedor",
    contrato_id: "ct-22",
    autor_membro_id: "mem-techminas-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-arcelormittal",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 5,
      comunicacao_empresa: 4,
      relacionamento_empresa: 5,
    },
    comentario: "Processo muito ágil. Detalhamento inicial poderia incluir histórico de falhas dos equipamentos.",
    status: "liberada",
    submetida_em: "2026-04-06",
    liberada_em: "2026-04-07",
  },
  // ct-23 — arcelormittal ↔ metalurgica-xyz (fornecedor)
  {
    id: "rev-ct-23-empresa",
    contrato_id: "ct-23",
    autor_membro_id: "mem-arcelormittal-owner",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-metalurgica-xyz",
    notas: {
      execucao: 5,
      prazo_execucao: 4,
      seguranca: 4,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 4,
    },
    comentario:
      "Fabricação de peças sob medida com tolerâncias dentro do especificado. Entrega 3 dias após o combinado.",
    status: "liberada",
    submetida_em: "2026-03-26",
    liberada_em: "2026-03-27",
  },
  {
    id: "rev-ct-23-fornecedor",
    contrato_id: "ct-23",
    autor_membro_id: "mem-metalurgica-xyz-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-arcelormittal",
    notas: {
      pagamento: 4,
      clareza_escopo: 4,
      respeito_cronograma: 5,
      comunicacao_empresa: 4,
      relacionamento_empresa: 4,
    },
    comentario: "Escopo técnico claro. Pagamento dentro do prazo contratado.",
    status: "liberada",
    submetida_em: "2026-03-26",
    liberada_em: "2026-03-27",
  },
  // ct-24 — usiminas ↔ ambiental
  {
    id: "rev-ct-24-empresa",
    contrato_id: "ct-24",
    autor_membro_id: "mem-usiminas-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-ambiental-solutions",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Monitoramento trimestral impecável. Relatórios detalhados e alertas proativos sobre limites ambientais.",
    status: "liberada",
    submetida_em: "2026-01-26",
    liberada_em: "2026-01-28",
  },
  {
    id: "rev-ct-24-fornecedor",
    contrato_id: "ct-24",
    autor_membro_id: "mem-ambiental-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-usiminas",
    notas: {
      pagamento: 4,
      clareza_escopo: 5,
      respeito_cronograma: 4,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Time técnico sênior e engajado. Algum atraso pontual nos ciclos de pagamento.",
    status: "liberada",
    submetida_em: "2026-01-27",
    liberada_em: "2026-01-28",
  },
  // ct-25 — usiminas ↔ translog
  {
    id: "rev-ct-25-empresa",
    contrato_id: "ct-25",
    autor_membro_id: "mem-usiminas-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-translog",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Operação logística contínua sem atrasos. Comunicação no dia a dia pode melhorar (prefiro updates proativos).",
    status: "liberada",
    submetida_em: "2026-03-04",
    liberada_em: "2026-03-05",
  },
  {
    id: "rev-ct-25-fornecedor",
    contrato_id: "ct-25",
    autor_membro_id: "mem-translog-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-usiminas",
    notas: {
      pagamento: 4,
      clareza_escopo: 4,
      respeito_cronograma: 4,
      comunicacao_empresa: 4,
      relacionamento_empresa: 5,
    },
    comentario: "Contrato estável. Cronograma de carregamentos poderia ser definido com mais antecedência.",
    status: "liberada",
    submetida_em: "2026-03-04",
    liberada_em: "2026-03-05",
  },
  // ct-26 — usiminas ↔ construminas
  {
    id: "rev-ct-26-empresa",
    contrato_id: "ct-26",
    autor_membro_id: "mem-usiminas-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-construminas",
    notas: {
      execucao: 4,
      prazo_execucao: 4,
      seguranca: 5,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Reforma estrutural com boa execução. Acerto fino na documentação de as-built demorou mais que o esperado.",
    status: "liberada",
    submetida_em: "2026-04-09",
    liberada_em: "2026-04-10",
  },
  {
    id: "rev-ct-26-fornecedor",
    contrato_id: "ct-26",
    autor_membro_id: "mem-construminas-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-usiminas",
    notas: {
      pagamento: 3,
      clareza_escopo: 4,
      respeito_cronograma: 4,
      comunicacao_empresa: 4,
      relacionamento_empresa: 4,
    },
    comentario: "Execução coordenada. Pagamento da última medição atrasou e impactou o fluxo de caixa.",
    status: "liberada",
    submetida_em: "2026-04-09",
    liberada_em: "2026-04-10",
  },
  // ct-27 — metalurgica-xyz (empresa) ↔ construminas
  {
    id: "rev-ct-27-empresa",
    contrato_id: "ct-27",
    autor_membro_id: "mem-metalurgica-xyz-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-construminas",
    notas: {
      execucao: 4,
      prazo_execucao: 4,
      seguranca: 5,
      comunicacao_fornecedor: 5,
      relacionamento_fornecedor: 5,
    },
    comentario:
      "Adequação de galpão entregue com qualidade. Pequenos ajustes finais precisaram de retrabalho.",
    status: "liberada",
    submetida_em: "2026-03-12",
    liberada_em: "2026-03-13",
  },
  {
    id: "rev-ct-27-fornecedor",
    contrato_id: "ct-27",
    autor_membro_id: "mem-construminas-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-metalurgica-xyz",
    notas: {
      pagamento: 5,
      clareza_escopo: 5,
      respeito_cronograma: 5,
      comunicacao_empresa: 5,
      relacionamento_empresa: 5,
    },
    comentario: "Decisões rápidas ao longo da obra. Excelente parceria.",
    status: "liberada",
    submetida_em: "2026-03-12",
    liberada_em: "2026-03-13",
  },
  // ct-28 — metalurgica-xyz (empresa) ↔ segwork
  {
    id: "rev-ct-28-empresa",
    contrato_id: "ct-28",
    autor_membro_id: "mem-metalurgica-xyz-admin",
    avaliado_org_tipo: "fornecedor",
    avaliado_org_id: "org-segwork",
    notas: {
      execucao: 5,
      prazo_execucao: 5,
      seguranca: 5,
      comunicacao_fornecedor: 4,
      relacionamento_fornecedor: 4,
    },
    comentario:
      "Laudos de SST entregues no prazo com alto rigor técnico. Feedback final poderia ter mais orientação prática.",
    status: "liberada",
    submetida_em: "2025-09-22",
    liberada_em: "2025-09-24",
  },
  {
    id: "rev-ct-28-fornecedor",
    contrato_id: "ct-28",
    autor_membro_id: "mem-segwork-owner",
    avaliado_org_tipo: "empresa",
    avaliado_org_id: "org-metalurgica-xyz",
    notas: {
      pagamento: 4,
      clareza_escopo: 4,
      respeito_cronograma: 5,
      comunicacao_empresa: 4,
      relacionamento_empresa: 4,
    },
    comentario: "Contratação organizada. Escopo inicial poderia especificar melhor as NRs aplicáveis.",
    status: "liberada",
    submetida_em: "2025-09-23",
    liberada_em: "2025-09-24",
  },
];

export function getReviewsByContrato(contrato_id: string): Review[] {
  return reviews.filter((r) => r.contrato_id === contrato_id);
}

export function getReviewsByAvaliado(
  avaliado_org_id: string,
  tipo: "empresa" | "fornecedor"
): Review[] {
  return reviews.filter(
    (r) =>
      r.avaliado_org_id === avaliado_org_id &&
      r.avaliado_org_tipo === tipo &&
      r.status === "liberada"
  );
}
